name: Deploying DIA to DEV

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: DEV
    steps:

    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main

    - name: 'Sign in via Azure CLI'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - run: |
        sudo docker build . -t testdiaacr.azurecr.io/diafrontend:${{ github.run_id }} 
        sudo docker push testdiaacr.azurecr.io/diafrontend:${{ github.run_id }}   

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'testdiafrontend'
        images: 'mycontainer.azurecr.io/diafrontend:${{ github.run_id }}'
