name: Deploy to Azure Web App

on:
  workflow_dispatch:

env:
  ACR_NAME: "mayurr"
  IMAGE_NAME: "frontend"
  TAG: "latest"
  APP_NAME: "mayurrpoc"
  RESOURCE_GROUP: "mayur-rg"
  REGION: "Canada Central"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: |
          az account set --subscription "${{ secrets.SUBSCRIPTION_ID }}"

      - name: Login to ACR
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Configure Web App to use Docker image from ACR
        run: |
          az webapp config container set \
            --name ${{ env.APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --container-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --container-registry-url https://${{ env.ACR_NAME }}.azurecr.io

      - name: Restart Web App to apply changes
        run: |
          az webapp restart --name ${{ env.APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}
