name: Deploying DIA Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (DEV, TEST, PROD)'
        required: true
        default: 'DEV'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      ENVIRONMENT: ${{ inputs.environment }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Set repository prefix based on environment'
        run: |
          REPO_PREFIX=$(echo "${{ env.ENVIRONMENT }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_PREFIX=$REPO_PREFIX" >> $GITHUB_ENV

      - name: 'Build Docker Image'
        run: |
          sudo docker build . -t $REPO_PREFIX/diafrontend:${{ github.run_id }}

      - name: 'Sign in via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Push Docker Image'
        run: |
          sudo docker push $REPO_PREFIX/diafrontend:${{ github.run_id }}

      # - name: 'Deploy to Azure Web App'
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'testdiafrontend' # Optional: Can be made dynamic too
      #     images: '${{ secrets.LOGIN_SERVER }}/${{ env.REPO_PREFIX }}/diafrontend:${{ github.run_id }}'
